apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-lazyload-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: radio
          name: jquery
          label: 是否引入 jquery
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
          help: "如果主题没有引入 jquery，需要在这里勾选开启"
        - $formkit: url
          name: img_error
          label: 图片加载失败图
          help: 图片加载失败时显示的图片
          placeholder: 请输入图片 url
