apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-lazyload-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: url
          name: loadingImg
          validation: "url"
          label: 加载图片
          help: "图片加载中时展示的图片，建议使用较低质量的图篇"
        - $formkit: url
          name: errorImg
          validation: "url"
          label: 图片加载失败图
          help: 图片加载失败时显示的图片